### Importing the libraries

In [ ]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
import re
from string import punctuation
import torch
import pandas as pd
from time import time
import seaborn as sns
import matplotlib.pyplot as plt
import tensorflow as tf
nltk.download("")

[nltk_data] Error loading : Package '' not found in index

False

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
tf.test.gpu_device_name()

''

### Loading the data

In [ ]:
df = pd.read_csv("drive/MyDrive/Extramarks Project/Dataset versions/Jee-clean_data-with-punct(untokenized).csv", )
df = df.drop("Unnamed: 0", axis = 1)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
len1 =len(df)
df = df.dropna()
print("Rows with NaN values: ", len1-len(df))

Rows with NaN values:  496

In [ ]:

df.head(2)

                                            question syllabus_id
0  Total number of species that can be oxidized b...      698013
1  How many following Ammonium salts will evolve ...      698013

In [ ]:
print(df.sample(1).iloc[0]['question'])
print(df.sample(1).iloc[0]['question'])
print(df.sample(1).iloc[0]['question'])
print(df.sample(1).iloc[0]['question'])
print(df.sample(1).iloc[0]['question'])

The below given diagram depicts an experiment to investigate the response of a plant stem to gravity stryde uploadfiles Image 2018 06 01 15278414541352780460 png Which among the following will act as a suitable control for this experiment
If the angular velocity of earth's spin is increased such that the bodies at the equator start floating the duration of the day would be approximately Take g 10ms 2 the radius of earth R 6400 103m Take Ï€ 3 14
In the external circuit the convention direction of current is the direction of flow of
Siddharth wants to use a markup language that will help him to display the output in the browser The language that is about displaying information is
à¤¡à¤¼ à¤”à¤° à¤¢à¤¼ à¤• à¤¸à¤• à¤µ à¤•à¤¸ à¤¤ à¤° à¤ª à¤¹

######Few samples

In [ ]:
df.iloc[-200:-190]

                                 question syllabus_id
276246                    sum of 3 and 5           -1
276247                  this is ates que           -1
276248                              test           -1
276249                              test           -1
276250                              test           -1
276251                president of india           -1
276252                president of india           -1
276253                president of india           -1
276254  who is the president of pakistan           -1
276255  who is the president of pakistan           -1

In [ ]:
df.iloc[-300:-290]

                                                 question syllabus_id
276146  This is the presentation ________________ Paya...        4413
276147        Keep your hair tied ______________ cooking         4413
276148              How _______________ this gadget work         4413
276149                   The house ___________ renovated         4413
276150              There were ______________ in my mind         4413
276151  John and Jenny are siblings and ____________ g...        4413
276152                       We _____________ for a trip         4413
276153                 Nothing ______________ your reach         4413
276154           My phone is not working _______________         4413
276155              The results ______________ announced         4413

In [ ]:
df.iloc[-500:-490]

                                                 question syllabus_id
275946      A seeker of truth in Jain religion is called       744375
275947       The correct adjective order is ____________         3620
275948              It was your __________________ fault         4415
275949   The sentence which is correct is ______________         3623
275950  à¤¯à¤¹ à¤« à¤² à¤¬à¤¹ à¤¤ à¤¸ à¤¦à¤° à¤¹ à¤¯à¤¹ à¤µ à¤• à¤¯ à¤¨ à¤® à¤¨à¤² à¤– à¤¤ à¤® à¤¸ à¤• à¤¯ à¤¹         5304
275951                     I can hear ____________ music         3651
275952        The rate of cooling of a liquid depends on         3838
275953  Sheetal did the assignment most elegantly Here...        3622
275954             à¤® à¤˜ à¤¦ à¤¡à¤¼ à¤°à¤¹ à¤¹ à¤‡à¤¸ à¤µ à¤• à¤¯ à¤® à¤• à¤¨ à¤¸ à¤…à¤¨ à¤µà¤¯ à¤¹         5304
275955  The comparative form of badly is _____________...        3623

### Cleaning the data

In [ ]:
removed_questions = []
questions_left = []

##### If there is a number in the question delete it

In [ ]:
for i in range(len(df)):
  if i % 20000 == 0:
    print("Index: ", i)
  patternDigit = re.compile(r'.*\d.*')
  row = df.iloc[i]
  question = row['question']
  # try:
  if len(patternDigit.findall(question)) > 0:
    removed_questions.append(row)
  else:
    questions_left.append(row)
  # except:
  #   print("Error at index: ", str(i), ", type: ", str(type(question)), ", question: " , str(question), ", row: " +str(row))
  #   removed_questions.append(row) 

print(len(removed_questions))
print(len(questions_left))

Index:  0
Index:  20000
Index:  40000
Index:  60000
Index:  80000
Index:  100000
Index:  120000
Index:  140000
Index:  160000
Index:  180000
Index:  200000
Index:  220000
Index:  240000
Index:  260000
117219
158732

Hence we remove 42% of the questions

##### If there are more than 3 numbers concsecutively in the question delete it

In [ ]:
# removed_questions = []
# questions_left = []

In [ ]:
# for i in range(len(df[:100000])):
#   if i % 20000 == 0:
#     print("Index: ", i)
#   patternDigit = re.compile(r'.*\d\d\d.*')
#   row = df.iloc[i]
#   question = row['question']
#   # try:
#   if len(patternDigit.findall(question)) > 0:
#     removed_questions.append(row)
#   else:
#     questions_left.append(row)
#   # except:
#   #   print("Error at index: ", str(i), ", type: ", str(type(question)), ", question: " , str(question), ", row: " +str(row))
#   #   removed_questions.append(row) 

# print(len(removed_questions))
# print(len(questions_left))

In [ ]:
# temp = []
# for i in range(len(df[:100000])):
#   if i % 20000 == 0:
#     print("Index: ", i)
#   patternDigit = re.compile(r'.*\d.*')
#   row = df.iloc[i]
#   question = row['question']
#   # try:
#   if len(patternDigit.findall(question)) > 0:
#     temp.append(row)
#   # except:
#   #   print("Error at index: ", str(i), ", type: ", str(type(question)), ", question: " , str(question), ", row: " +str(row))
#   #   removed_questions.append(row) 

# print(len(temp))

In [ ]:
# pd.DataFrame(temp)

Hence we remove 20% of the questions

##### If there is a non-ASCII charater in the question delete it 
The devanagri chars have the unicod eindexes 0900 - 097F according to [stackoverflow](https://stackoverflow.com/questions/41356013/how-to-detect-if-a-string-contains-hindi-devnagri-in-it-with-character-and-wor)

In [ ]:
cleanDf = pd.DataFrame(questions_left)
questions_left = []

In [ ]:
for i in range(len(cleanDf)):
  if i % 20000 == 0:
    print("Index: ", i)
  patternHindi = re.compile(r'.*[\u0900-\u097F].*') 
  row = cleanDf.iloc[i]
  question = row['question']
  
  if len(patternHindi.findall(question)) > 0:
    removed_questions.append(row)
  else:
    questions_left.append(row)
  

print(len(removed_questions))
print(len(questions_left))

Index:  0
Index:  20000
Index:  40000
Index:  60000
Index:  80000
Index:  100000
Index:  120000
Index:  140000
141195
134756

##### Replacing all element shortcuts with their full forms

In [ ]:
cleanDf = pd.DataFrame(questions_left)
questions_left = []

In [ ]:
zync potassium

In [ ]:
cleanDf

                                                 question syllabus_id
7              How many Ï€ bonds are present in ferrocene       700295
10      What is covalency of chlorine atom in second e...      698013
25      In solid X atoms goes to corner of the cube an...      700078
28      Calculate value of x y here x and y are the to...      697895
40      In phosphorus acid if X is number of non bondi...      697895
...                                                   ...         ...
276441                       subjective english question           -1
276442                       question subjective english           -1
276443                      subjective english questions           -1
276445                                              test           -1
276446                           paragraph question text    (1, 2, 3)

[134756 rows x 2 columns]

Warning: total number of rows (134756) exceeds max_rows (20000). Limiting to first (20000) rows.

In [ ]:
cleanDf[-20000:]

                                                 question syllabus_id
245116  A parallel plate condenser with dielectric of ...        4174
245117  The energy required to charge a parallel plate...        4174
245118                   To store electric charge we use         4174
245119                  One micro microfarad is equal to         4174
245120  After an isolated conducting sphere is given a...        4174
...                                                   ...         ...
276441                       subjective english question           -1
276442                       question subjective english           -1
276443                      subjective english questions           -1
276445                                              test           -1
276446                           paragraph question text    (1, 2, 3)

[20000 rows x 2 columns]

In [ ]:
len(cleanDf)

134756

### Saving as file

In [ ]:
cleanDf.to_csv("drive/MyDrive/Extramarks Project/Dataset versions/EM-String-only-questions(cleanDf).csv")